---
lang: en
title: openSUSE Kernel
title_short: Kernel
description: openSUSE Kernel Site
copyright: "© 2011–2020 openSUSE Contributors"
url: https://kernel.opensuse.org
navbar_links:
- text: openSUSE
  children:
  - text: master
    link: master.html
  - text: stable
    link: stable.html
- text: upstream
  children:
  - text: linux-next
    link: linux-next.html
  - text: vanilla
    link: vanilla.html
- text: SLE
  children:
  - text: SLE15-SP6
    link: SLE15-SP6.html
  - text: SLE15-SP5
    link: SLE15-SP5.html
  - text: SLE15-SP4
    link: SLE15-SP4.html
  - text: SLE12-SP5
    link: SLE12-SP5.html
- text: SLE Addons
  children:
  - text: SLE15-SP6-RT
    link: SLE15-SP6-RT.html
  - text: SLE15-SP6-AZURE
    link: SLE15-SP6-AZURE.html
  - text: SLE15-SP5-RT
    link: SLE15-SP5-RT.html
  - text: SLE15-SP5-AZURE
    link: SLE15-SP5-AZURE.html
  - text: SLE15-SP4-RT
    link: SLE15-SP4-RT.html
  - text: SLE15-SP4-AZURE
    link: SLE15-SP4-AZURE.html
  - text: SLE15-SP3-RT
    link: SLE15-SP3-RT.html
  - text: SLE15-SP2-EB
    link: SLE15-SP2-EB.html
  - text: SLE12-SP5-RT
    link: SLE12-SP5-RT.html
  - text: SLE12-SP5-AZURE
    link: SLE12-SP5-AZURE.html
- text: SLE Live Patching
  children:
  - text: SLE15-SP5
    link: SLE15-SP5-lp.html
  - text: SLE15-SP4
    link: SLE15-SP4-lp.html
  - text: SLE12-SP5
    link: SLE12-SP5-lp.html
  - text: SLE15-SP5-RT
    link: SLE15-SP5-RT-lp.html
  - text: SLE15-SP4-RT
    link: SLE15-SP4-RT-lp.html
footer_links:
- text: Source Code
  link: https://github.com/openSUSE/kernel-pages
plugins:
- jekyll-redirect-from
search_provider: github
search_github_repo: openSUSE/kernel-pages
remote_theme: openSUSE/jekyll-theme
defaults:
- scope:
    path: "*.md"
  values:
    layout: markdown
exclude:
- README.md
- Gemfile
- Gemfile.lock
- vendor
